version: "3.9"
   
services:
  backend:
    restart: on-failure
    container_name: backend
    command : bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./Backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    restart: on-failure
    command : npm start
    container_name: front
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes: 
      - static_volume:/app/backend/static
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend

volumes: 
  static_volume:
